<?php

// Validation scenarios: schema, rule sets and message levels per kind of document.
// Generated - do not edit.

return [
    'kosit' => [
        [
            'name' => 'EN16931 XRechnung (UBL Invoice)',
            'profile' => 'XRECHNUNG',
            'root' => '{urn:oasis:names:specification:ubl:schema:xsd:Invoice-2}Invoice',
            'path' => ['{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}CustomizationID'],
            'compare' => 'string',
            'identifier' => 'urn:cen.eu:en16931:2017#compliant#urn:xeinkauf.de:kosit:xrechnung_3.0',
            'schema' => 'resources/kosit-validator/resources/ubl/2.1/xsd/maindoc/UBL-Invoice-2.1.xsd',
            'rules' => ['en16931-ubl','xrechnung-ubl'],
            'levels' => ['BR-CL-23'=>'warning','BR-CL-21'=>'warning','UBL-CR-646'=>'error'],
        ],
        [
            'name' => 'EN16931 XRechnung Extension (UBL Invoice)',
            'profile' => 'XRECHNUNG',
            'root' => '{urn:oasis:names:specification:ubl:schema:xsd:Invoice-2}Invoice',
            'path' => ['{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}CustomizationID'],
            'compare' => 'string',
            'identifier' => 'urn:cen.eu:en16931:2017#compliant#urn:xeinkauf.de:kosit:xrechnung_3.0#conformant#urn:xeinkauf.de:kosit:extension:xrechnung_3.0',
            'schema' => 'resources/kosit-validator/resources/ubl/2.1/xsd/maindoc/UBL-Invoice-2.1.xsd',
            'rules' => ['en16931-ubl','xrechnung-ubl'],
            'levels' => ['BR-CL-21'=>'information','BR-CL-23'=>'warning','BR-CL-24'=>'information','BR-CL-10'=>'information','BR-CL-11'=>'information','BR-CL-25'=>'information','BR-CL-26'=>'information','BR-CO-16'=>'information','UBL-CR-470'=>'information','UBL-CR-646'=>'information'],
        ],
        [
            'name' => 'EN16931 XRechnung CVD (UBL Invoice)',
            'profile' => 'XRECHNUNG',
            'root' => '{urn:oasis:names:specification:ubl:schema:xsd:Invoice-2}Invoice',
            'path' => ['{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}CustomizationID'],
            'compare' => 'string',
            'identifier' => 'urn:cen.eu:en16931:2017#compliant#urn:xeinkauf.de:kosit:xrechnung_3.0#compliant#urn:xeinkauf.de:kosit:xrechnung:cvd_0.9',
            'schema' => 'resources/kosit-validator/resources/ubl/2.1/xsd/maindoc/UBL-Invoice-2.1.xsd',
            'rules' => ['en16931-ubl','xrechnung-ubl'],
            'levels' => ['BR-CL-13'=>'information','BR-CL-23'=>'warning','BR-CL-21'=>'warning','UBL-CR-646'=>'error'],
        ],
        [
            'name' => 'EN16931 XRechnung (UBL CreditNote)',
            'profile' => 'XRECHNUNG',
            'root' => '{urn:oasis:names:specification:ubl:schema:xsd:CreditNote-2}CreditNote',
            'path' => ['{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}CustomizationID'],
            'compare' => 'text',
            'identifier' => 'urn:cen.eu:en16931:2017#compliant#urn:xeinkauf.de:kosit:xrechnung_3.0',
            'schema' => 'resources/kosit-validator/resources/ubl/2.1/xsd/maindoc/UBL-CreditNote-2.1.xsd',
            'rules' => ['en16931-ubl','xrechnung-ubl'],
            'levels' => ['BR-CL-23'=>'warning','BR-CL-21'=>'warning'],
        ],
        [
            'name' => 'EN16931 XRechnung CVD (UBL CreditNote)',
            'profile' => 'XRECHNUNG',
            'root' => '{urn:oasis:names:specification:ubl:schema:xsd:CreditNote-2}CreditNote',
            'path' => ['{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}CustomizationID'],
            'compare' => 'text',
            'identifier' => 'urn:cen.eu:en16931:2017#compliant#urn:xeinkauf.de:kosit:xrechnung_3.0#compliant#urn:xeinkauf.de:kosit:xrechnung:cvd_0.9',
            'schema' => 'resources/kosit-validator/resources/ubl/2.1/xsd/maindoc/UBL-CreditNote-2.1.xsd',
            'rules' => ['en16931-ubl','xrechnung-ubl'],
            'levels' => ['BR-CL-13'=>'information','BR-CL-23'=>'warning','BR-CL-21'=>'warning','UBL-CR-646'=>'error'],
        ],
        [
            'name' => 'EN16931 XRechnung (CII)',
            'profile' => 'XRECHNUNG',
            'root' => '{urn:un:unece:uncefact:data:standard:CrossIndustryInvoice:100}CrossIndustryInvoice',
            'path' => ['{urn:un:unece:uncefact:data:standard:CrossIndustryInvoice:100}ExchangedDocumentContext','{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100}GuidelineSpecifiedDocumentContextParameter','{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100}ID'],
            'compare' => 'text',
            'identifier' => 'urn:cen.eu:en16931:2017#compliant#urn:xeinkauf.de:kosit:xrechnung_3.0',
            'schema' => 'resources/kosit-validator/resources/cii/16b/xsd/CrossIndustryInvoice_100pD16B.xsd',
            'rules' => ['en16931-cii','xrechnung-cii'],
            'levels' => ['BR-CL-23'=>'warning','BR-CL-21'=>'warning','CII-SR-452'=>'error','CII-SR-453'=>'error','CII-SR-454'=>'error','CII-SR-465'=>'error','CII-SR-466'=>'error','CII-SR-475'=>'information','CII-SR-476'=>'information'],
        ],
        [
            'name' => 'EN16931 XRechnung Extension (CII)',
            'profile' => 'XRECHNUNG',
            'root' => '{urn:un:unece:uncefact:data:standard:CrossIndustryInvoice:100}CrossIndustryInvoice',
            'path' => ['{urn:un:unece:uncefact:data:standard:CrossIndustryInvoice:100}ExchangedDocumentContext','{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100}GuidelineSpecifiedDocumentContextParameter','{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100}ID'],
            'compare' => 'text',
            'identifier' => 'urn:cen.eu:en16931:2017#compliant#urn:xeinkauf.de:kosit:xrechnung_3.0#conformant#urn:xeinkauf.de:kosit:extension:xrechnung_3.0',
            'schema' => 'resources/kosit-validator/resources/cii/16b/xsd/CrossIndustryInvoice_100pD16B.xsd',
            'rules' => ['en16931-cii','xrechnung-cii'],
            'levels' => ['BR-CL-23'=>'warning','BR-CL-21'=>'information','BR-CL-11'=>'information','BR-CL-10'=>'information','BR-CL-24'=>'information','BR-CL-25'=>'information','BR-CL-26'=>'information','CII-SR-452'=>'error','CII-SR-453'=>'error','CII-SR-454'=>'error','CII-SR-465'=>'error','CII-SR-466'=>'error','CII-SR-475'=>'information','CII-SR-476'=>'information'],
        ],
        [
            'name' => 'EN16931 XRechnung CVD (CII)',
            'profile' => 'XRECHNUNG',
            'root' => '{urn:un:unece:uncefact:data:standard:CrossIndustryInvoice:100}CrossIndustryInvoice',
            'path' => ['{urn:un:unece:uncefact:data:standard:CrossIndustryInvoice:100}ExchangedDocumentContext','{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100}GuidelineSpecifiedDocumentContextParameter','{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100}ID'],
            'compare' => 'text',
            'identifier' => 'urn:cen.eu:en16931:2017#compliant#urn:xeinkauf.de:kosit:xrechnung_3.0#compliant#urn:xeinkauf.de:kosit:xrechnung:cvd_0.9',
            'schema' => 'resources/kosit-validator/resources/cii/16b/xsd/CrossIndustryInvoice_100pD16B.xsd',
            'rules' => ['en16931-cii','xrechnung-cii'],
            'levels' => ['BR-CL-13'=>'information','BR-CL-23'=>'warning','BR-CL-21'=>'warning','CII-SR-452'=>'error','CII-SR-453'=>'error','CII-SR-454'=>'error','CII-SR-465'=>'error','CII-SR-466'=>'error','CII-SR-475'=>'information','CII-SR-476'=>'information'],
        ],
        [
            'name' => 'EN16931 (UBL Invoice)',
            'profile' => 'CORE',
            'root' => '{urn:oasis:names:specification:ubl:schema:xsd:Invoice-2}Invoice',
            'path' => ['{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}CustomizationID'],
            'compare' => 'text',
            'identifier' => 'urn:cen.eu:en16931:2017',
            'schema' => 'resources/kosit-validator/resources/ubl/2.1/xsd/maindoc/UBL-Invoice-2.1.xsd',
            'rules' => ['en16931-ubl'],
            'levels' => [],
        ],
        [
            'name' => 'EN16931 (UBL CreditNote)',
            'profile' => 'CORE',
            'root' => '{urn:oasis:names:specification:ubl:schema:xsd:CreditNote-2}CreditNote',
            'path' => ['{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}CustomizationID'],
            'compare' => 'text',
            'identifier' => 'urn:cen.eu:en16931:2017',
            'schema' => 'resources/kosit-validator/resources/ubl/2.1/xsd/maindoc/UBL-CreditNote-2.1.xsd',
            'rules' => ['en16931-ubl'],
            'levels' => [],
        ],
        [
            'name' => 'EN16931 (CII)',
            'profile' => 'CORE',
            'root' => '{urn:un:unece:uncefact:data:standard:CrossIndustryInvoice:100}CrossIndustryInvoice',
            'path' => ['{urn:un:unece:uncefact:data:standard:CrossIndustryInvoice:100}ExchangedDocumentContext','{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100}GuidelineSpecifiedDocumentContextParameter','{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100}ID'],
            'compare' => 'text',
            'identifier' => 'urn:cen.eu:en16931:2017',
            'schema' => 'resources/kosit-validator/resources/cii/16b/xsd/CrossIndustryInvoice_100pD16B.xsd',
            'rules' => ['en16931-cii'],
            'levels' => [],
        ],
    ],
    'peppol' => [
        [
            'name' => 'Peppol BIS Billing 3.0 (UBL Invoice)',
            'profile' => 'PEPPOL',
            'root' => '{urn:oasis:names:specification:ubl:schema:xsd:Invoice-2}Invoice',
            'path' => ['{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}CustomizationID'],
            'compare' => 'string',
            'identifier' => 'urn:cen.eu:en16931:2017#compliant#urn:fdc:peppol.eu:2017:poacc:billing:3.0',
            'schema' => 'resources/kosit-validator/resources/ubl/2.1/xsd/maindoc/UBL-Invoice-2.1.xsd',
            'rules' => ['en16931-ubl','peppol-ubl'],
            'levels' => [],
        ],
        [
            'name' => 'Peppol BIS Billing 3.0 (UBL CreditNote)',
            'profile' => 'PEPPOL',
            'root' => '{urn:oasis:names:specification:ubl:schema:xsd:CreditNote-2}CreditNote',
            'path' => ['{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}CustomizationID'],
            'compare' => 'string',
            'identifier' => 'urn:cen.eu:en16931:2017#compliant#urn:fdc:peppol.eu:2017:poacc:billing:3.0',
            'schema' => 'resources/kosit-validator/resources/ubl/2.1/xsd/maindoc/UBL-CreditNote-2.1.xsd',
            'rules' => ['en16931-ubl','peppol-ubl'],
            'levels' => [],
        ],
        [
            'name' => 'Peppol BIS Billing 3.0 (CII)',
            'profile' => 'PEPPOL',
            'root' => '{urn:un:unece:uncefact:data:standard:CrossIndustryInvoice:100}CrossIndustryInvoice',
            'path' => ['{urn:un:unece:uncefact:data:standard:CrossIndustryInvoice:100}ExchangedDocumentContext','{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100}GuidelineSpecifiedDocumentContextParameter','{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100}ID'],
            'compare' => 'string',
            'identifier' => 'urn:cen.eu:en16931:2017#compliant#urn:fdc:peppol.eu:2017:poacc:billing:3.0',
            'schema' => 'resources/kosit-validator/resources/cii/16b/xsd/CrossIndustryInvoice_100pD16B.xsd',
            'rules' => ['en16931-cii','peppol-cii'],
            'levels' => [],
        ],
    ],
    'ferd' => [
        'MINIMUM' => [
            'version' => '1.09.2',
            'schema' => 'resources/ferd/schema/MINIMUM/Factur-X_1.09.2_MINIMUM.xsd',
            'rules' => ['facturx-minimum'],
        ],
        'BASIC WL' => [
            'version' => '1.09.2',
            'schema' => 'resources/ferd/schema/BASICWL/Factur-X_1.09.2_BASICWL.xsd',
            'rules' => ['facturx-basicwl'],
        ],
        'BASIC' => [
            'version' => '1.09.2',
            'schema' => 'resources/ferd/schema/BASIC/Factur-X_1.09.2_BASIC.xsd',
            'rules' => ['facturx-basic'],
        ],
        'EN16931' => [
            'version' => '1.09.2',
            'schema' => 'resources/ferd/schema/EN16931/Factur-X_1.09.2_EN16931.xsd',
            'rules' => ['facturx-en16931'],
        ],
        'EXTENDED' => [
            'version' => '1.09.2',
            'schema' => 'resources/ferd/schema/EXTENDED/Factur-X_1.09.2_EXTENDED.xsd',
            'rules' => ['facturx-extended'],
        ],
    ],
];
