<?php

// EN 16931 semantic model (KoSIT xrechnung-semantic-model.xsd): element names, BT/BG ids, cardinality, types.
// Generated - do not edit.

return [
    'root' => 'invoice',
    'types' => [
        'INVOICE_NOTEType' => [
            'Invoice_note_subject_code' => [
                'id' => 'BT-21',
                'type' => 'code',
                'min' => 1,
                'multiple' => false,
                'description' => 'Der Betreff für den nachfolgenden Textvermerk zur Rechnung. Anmerkung: Die Auswahl erfolgt aus UNTDID 4451.',
            ],
            'Invoice_note' => [
                'id' => 'BT-22',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Ein Textvermerk, der unstrukturierte Informationen enthält, die für die Rechnung als Ganzes maßgeblich sind. Erforderlichenfalls können Angaben zur Aufbewahrungspflicht gem. § 14 Abs. 4 UStG hier aufgenommen werden. Anmerkung: Im Falle einer bereits fakturierten Rechnung kann hier z. B. der Grund der Korrektur angegeben werden.',
            ],
        ],
        'PROCESS_CONTROLType' => [
            'Business_process_type' => [
                'id' => 'BT-23',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Identifiziert den Kontext des Geschäftsprozesses, in dem die Transaktion erfolgt. Er ermöglicht es dem Erwerber, die Rechnung in angemessener Weise zu verarbeiten. Anmerkung: Die mit diesem Informationselement zu übermittelnde Angabe wird vom Erwerber spezifiziert.',
            ],
            'Specification_identifier' => [
                'id' => 'BT-24',
                'type' => 'identifier',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine Kennung der Spezifikation, die das gesamte Regelwerk zum semantischen Inhalt, zu den Kardinalitäten und den Geschäftsregeln enthält, denen die in der Rechnung enthaltenen Daten entsprechen. Anmerkung: Damit wird die Konformität zum jeweiligen Dokument erklärt. Für den Verweis auf die EU-Norm ist urn:cen.eu:en16931:2017 anzugeben. Rechnungen, die zum Standard XRechnung konform sind, geben hier urn:cen.eu:en16931:2017#compliant#urn:xoev-de:kosit:standard:xrechnung_1.2 an. Es ist kein Schema zu verwenden.',
            ],
        ],
        'PRECEDING_INVOICE_REFERENCEType' => [
            'Preceding_Invoice_reference' => [
                'id' => 'BT-25',
                'type' => 'document_reference',
                'min' => 1,
                'multiple' => false,
                'description' => 'Die Kennung der vorausgegangenen Rechnung, auf die Bezug genommen wird.',
            ],
            'Preceding_Invoice_issue_date' => [
                'id' => 'BT-26',
                'type' => 'date',
                'min' => 1,
                'multiple' => false,
                'description' => 'Das Datum, zu dem die vorausgegangene Rechnung ausgestellt wurde. Anmerkung: Für den Fall, dass die Nummer der vorausgegangenen Rechnung (Preceding invoice identifier) nicht eindeutig ist, soll das Datum der vorausgegangenen Rechnung (Preceding invoice issue date) angegeben werden.',
            ],
        ],
        'SELLERType' => [
            'Seller_name' => [
                'id' => 'BT-27',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Der vollständige Name, unter dem der Verkäufer im nationalen Register für juristische Personen oder als steuerpflichtige Person eingetragen ist oder anderweitig als Person(en) handelt (Firma).',
            ],
            'Seller_trading_name' => [
                'id' => 'BT-28',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Ein Name, unter dem der Verkäufer bekannt ist, sofern abweichend vom Namen des Verkäufers.',
            ],
            'Seller_identifier' => [
                'id' => 'BT-29',
                'type' => 'identifier',
                'min' => 1,
                'multiple' => true,
                'description' => 'Eine (i. d. R. vom Erwerber vergebene) Kennung des Verkäufers, wie z. B. die Kreditorennummer für das Mittelbewirtschaftungsverfahren oder die Lieferantennummer für das Bestellsystem.',
            ],
            'Seller_legal_registration_identifier' => [
                'id' => 'BT-30',
                'type' => 'identifier',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine von einer offiziellen Registrierstelle ausgegebene Kennung, die den Verkäufer als Rechtsträger oder juristische Person identifiziert.',
            ],
            'Seller_VAT_identifier' => [
                'id' => 'BT-31',
                'type' => 'identifier',
                'min' => 1,
                'multiple' => false,
                'description' => 'Die Umsatzsteuer-Identifikationsnummer des Verkäufers. Verfügt der Verkäufer über eine solche, ist sie hier anzugeben, sofern nicht Angaben zum Seller tax representative gemacht werden.',
            ],
            'Seller_tax_registration_identifier' => [
                'id' => 'BT-32',
                'type' => 'identifier',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine örtliche steuerrechtliche Kennung des Verkäufers (bestimmt durch dessen Adresse) oder ein Verweis auf seinen eingetragenen Steuerstatus. (Hier ist ggf. die Angabe «Steuerschuldnerschaft des Leistungsempfängers» oder die USt-Befreiung des Rechnungsstellers einzutragen.)',
            ],
            'Seller_additional_legal_information' => [
                'id' => 'BT-33',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Weitere rechtliche Informationen, die für den Verkäufer maßgeblich sind (wie z. B. Grundkapital).',
            ],
            'Seller_electronic_address' => [
                'id' => 'BT-34',
                'type' => 'identifier',
                'min' => 1,
                'multiple' => false,
                'description' => 'Gibt die elektronische Adresse des Verkäufers an, an die die Antwort der Anwendungsebene auf eine Rechnung gesendet werden kann.',
            ],
            'SELLER_POSTAL_ADDRESS' => [
                'id' => 'BG-5',
                'type' => 'SELLER_POSTAL_ADDRESSType',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine Gruppe von Informationselementen, die Informationen über die Verkäuferanschrift liefern.',
            ],
            'SELLER_CONTACT' => [
                'id' => 'BG-6',
                'type' => 'SELLER_CONTACTType',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine Gruppe von Informationselementen, die Kontaktinformationen des Verkäufers enthalten.',
            ],
        ],
        'SELLER_POSTAL_ADDRESSType' => [
            'Seller_address_line_1' => [
                'id' => 'BT-35',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Die Hauptzeile in einer Anschrift. Üblicherweise ist dies entweder Strasse und Hausnummer oder der Text "Postfach" gefolgt von der Postfachnummer.',
            ],
            'Seller_address_line_2' => [
                'id' => 'BT-36',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine zusätzliche Adresszeile in einer Anschrift, die verwendet werden kann, um weitere Einzelheiten in Ergänzung zur Hauptzeile anzugeben.',
            ],
            'Seller_address_line_3' => [
                'id' => 'BT-162',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine zusätzliche Adresszeile in einer Anschrift, die verwendet werden kann, um weitere Einzelheiten in Ergänzung zur Hauptzeile anzugeben.',
            ],
            'Seller_city' => [
                'id' => 'BT-37',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Die Bezeichnung der Stadt oder Gemeinde, in der sich die Verkäuferanschrift befindet.',
            ],
            'Seller_post_code' => [
                'id' => 'BT-38',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Der Bezeichner für eine dem zuständigen Postdienst entsprechend adressierbare Gruppe von Eigenschaften.',
            ],
            'Seller_country_subdivision' => [
                'id' => 'BT-39',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Die Unterteilung eines Landes (wie Region, Bundesland, Provinz etc.).',
            ],
            'Seller_country_code' => [
                'id' => 'BT-40',
                'type' => 'code',
                'min' => 1,
                'multiple' => false,
                'description' => 'Ein Code, mit dem das Land bezeichnet wird. Anmerkung: Die Liste der zulässigen Länder ist bei der ISO 3166-1 «Codes for the representation of names of countries and their subdivisions» erhältlich. Nur die Alpha-2-Darstellung darf verwendet werden.',
            ],
        ],
        'SELLER_CONTACTType' => [
            'Seller_contact_point' => [
                'id' => 'BT-41',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Angaben zu Ansprechpartner oder Kontaktstelle (wie z. B. Name einer Person, Abteilungs- oder Bürobezeichnung).',
            ],
            'Seller_contact_telephone_number' => [
                'id' => 'BT-42',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Telefonnummer des Ansprechpartners oder der Kontaktstelle',
            ],
            'Seller_contact_email_address' => [
                'id' => 'BT-43',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine E-Mail-Adresse des Ansprechpartners oder der Kontaktstelle.',
            ],
        ],
        'BUYERType' => [
            'Buyer_name' => [
                'id' => 'BT-44',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Der vollständige Name des Erwerbers.',
            ],
            'Buyer_trading_name' => [
                'id' => 'BT-45',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Ein Name, unter dem der Erwerber bekannt ist, sofern abweichend vom Namen des Erwerbers.',
            ],
            'Buyer_identifier' => [
                'id' => 'BT-46',
                'type' => 'identifier',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine (i. d. R. vom Verkäufer vergebene) Kennung des Erwerbers, wie z. B. die Debitorennummer für die Buchhaltung oder die Kundennnummer für die Auftragsverwaltung. Anmerkung: Für die Bildung des Buyer Identifier ist kein einheitliches Schema erforderlich.',
            ],
            'Buyer_legal_registration_identifier' => [
                'id' => 'BT-47',
                'type' => 'identifier',
                'min' => 1,
                'multiple' => false,
                'description' => 'Ein von einer offiziellen Registrierstelle ausgegebener Bezeichner, der den Erwerber als Rechtsträger oder juristische Person identifiziert. Z. B. Handelsregister-Eintrag, Vereinsregister etc.',
            ],
            'Buyer_VAT_identifier' => [
                'id' => 'BT-48',
                'type' => 'identifier',
                'min' => 1,
                'multiple' => false,
                'description' => 'Die Umsatzsteuer-Identifikationsnummer des Erwerbers.',
            ],
            'Buyer_electronic_address' => [
                'id' => 'BT-49',
                'type' => 'identifier',
                'min' => 1,
                'multiple' => false,
                'description' => 'Gibt eine elektronische Adresse des Erwerbers an, an die eine Rechnung gesendet werden sollte.',
            ],
            'BUYER_POSTAL_ADDRESS' => [
                'id' => 'BG-8',
                'type' => 'BUYER_POSTAL_ADDRESSType',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine Gruppe von Informationselementen, die Informationen über die Anschrift des Erwerbers liefern. Anmerkung: Es ist eine gültige vollständige Anschrift anzugeben.',
            ],
            'BUYER_CONTACT' => [
                'id' => 'BG-9',
                'type' => 'BUYER_CONTACTType',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine Gruppe von Informationselementen, die Angaben zum Ansprechpartner oder der Kontaktstelle beim Erwerber liefern.',
            ],
        ],
        'BUYER_POSTAL_ADDRESSType' => [
            'Buyer_address_line_1' => [
                'id' => 'BT-50',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Die Hauptzeile einer Anschrift. Üblicherweise ist dies entweder Strasse und Hausnummer oder der Text "Postfach" gefolgt von der Postfachnummer.',
            ],
            'Buyer_address_line_2' => [
                'id' => 'BT-51',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine zusätzliche Adresszeile in einer Anschrift, die verwendet werden kann, um weitere Einzelheiten in Ergänzung zur Hauptzeile anzugeben.',
            ],
            'Buyer_address_line_3' => [
                'id' => 'BT-163',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine zusätzliche Adresszeile in einer Anschrift, die verwendet werden kann, um weitere Einzelheiten in Ergänzung zur Hauptzeile anzugeben.',
            ],
            'Buyer_city' => [
                'id' => 'BT-52',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Die Bezeichnung der Stadt oder Gemeinde, in der sich die Erwerberanschrift befindet.',
            ],
            'Buyer_post_code' => [
                'id' => 'BT-53',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Der Bezeichner für eine dem zuständigen Postdienst entsprechend adressierbare Gruppe von Eigenschaften.',
            ],
            'Buyer_country_subdivision' => [
                'id' => 'BT-54',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Die Unterteilung eines Landes (wie Region, Bundesland, Provinz etc.).',
            ],
            'Buyer_country_code' => [
                'id' => 'BT-55',
                'type' => 'code',
                'min' => 1,
                'multiple' => false,
                'description' => 'Ein Code, mit dem das Land bezeichnet wird. Anmerkung: Die Liste der zulässigen Länder ist bei der ISO 3166-1 «Codes for the representation of names of countries and their subdivisions» erhältlich. Nur die Alpha-2-Darstellung darf verwendet werden.',
            ],
        ],
        'BUYER_CONTACTType' => [
            'Buyer_contact_point' => [
                'id' => 'BT-56',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Ansprechpartner oder Kontaktstelle beim Erwerber (wie z. B. Name einer Person, Abteilungs- oder Bürobezeichnung).',
            ],
            'Buyer_contact_telephone_number' => [
                'id' => 'BT-57',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine Telefonnummer der Kontaktstelle.',
            ],
            'Buyer_contact_email_address' => [
                'id' => 'BT-58',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine E-Mail-Adresse der Kontaktstelle.',
            ],
        ],
        'PAYEEType' => [
            'Payee_name' => [
                'id' => 'BT-59',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Der Name des Zahlungsempfängers. Anmerkung: Wird verwendet, wenn der Zahlungsempfänger nicht mit dem Verkäufer identisch ist. Gleichwohl kann der Name des Zahlungsempfänger identisch sein mit dem Namen des Verkäufers.',
            ],
            'Payee_identifier' => [
                'id' => 'BT-60',
                'type' => 'identifier',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine Kennung für den Zahlungsempfänger. Anmerkung: Wenn kein Schema verwendet wird, sollte die Kennung Erwerber und Verkäufer bekannt sein, z. B. eine von Verkäufer oder Erwerber zugewiesene Kennung.',
            ],
            'Payee_legal_registration_identifier' => [
                'id' => 'BT-61',
                'type' => 'identifier',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine von einer offiziellen Registrierstelle ausgegebene Kennung, die den Zahlungsempfänger als einen Rechtsträger oder eine juristische Person identifiziert.',
            ],
        ],
        'SELLER_TAX_REPRESENTATIVE_PARTYType' => [
            'Seller_tax_representative_name' => [
                'id' => 'BT-62',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Der vollständige Name des Steuervertreters des Verkäufers.',
            ],
            'Seller_tax_representative_VAT_identifier' => [
                'id' => 'BT-63',
                'type' => 'identifier',
                'min' => 1,
                'multiple' => false,
                'description' => 'Die Umsatzsteuer-Identifikationsnummer des Steuervertreters des Verkäufers.',
            ],
            'SELLER_TAX_REPRESENTATIVE_POSTAL_ADDRESS' => [
                'id' => 'BG-12',
                'type' => 'SELLER_TAX_REPRESENTATIVE_POSTAL_ADDRESSType',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine Gruppe von Informationselementen, die Informationen über die Postanschrift des Steuervertreters liefern.',
            ],
        ],
        'SELLER_TAX_REPRESENTATIVE_POSTAL_ADDRESSType' => [
            'Tax_representative_address_line_1' => [
                'id' => 'BT-64',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Die Hauptzeile in einer Anschrift. Üblicherweise ist dies entweder Strasse und Hausnummer oder der Text "Postfach" gefolgt von der Postfachnummer.',
            ],
            'Tax_representative_address_line_2' => [
                'id' => 'BT-65',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine zusätzliche Adresszeile in einer Anschrift, die verwendet werden kann, um weitere Einzelheiten in Ergänzung zur Hauptzeile anzugeben.',
            ],
            'Tax_representative_address_line_3' => [
                'id' => 'BT-164',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine zusätzliche Adresszeile in einer Anschrift, die verwendet werden kann, um weitere Einzelheiten in Ergänzung zur Hauptzeile anzugeben.',
            ],
            'Tax_representative_city' => [
                'id' => 'BT-66',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Die Bezeichnung der Stadt oder Gemeinde, in der sich die Anschrift des Steuervertreters befindet.',
            ],
            'Tax_representative_post_code' => [
                'id' => 'BT-67',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Der Bezeichner für eine dem zuständigen Postdienst entsprechend adressierbare Gruppe von Eigenschaften.',
            ],
            'Tax_representative_country_subdivision' => [
                'id' => 'BT-68',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Die Unterteilung eines Landes.',
            ],
            'Tax_representative_country_code' => [
                'id' => 'BT-69',
                'type' => 'code',
                'min' => 1,
                'multiple' => false,
                'description' => 'Ein Code, mit dem das Land bezeichnet wird. Anmerkung: Die Liste der zulässigen Länder ist bei der ISO 3166-1 «Codes for the representation of names of countries and their subdivisions» erhältlich. Nur die Alpha-2-Darstellung darf verwendet werden.',
            ],
        ],
        'DELIVERY_INFORMATIONType' => [
            'Deliver_to_party_name' => [
                'id' => 'BT-70',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Der Name des Empfängers, an den die Waren geliefert bzw. für den die Dienstleistungen erbracht werden. Das Informationselement ist zu verwenden, wenn der Empfänger vom Erwerber abweicht.',
            ],
            'Deliver_to_location_identifier' => [
                'id' => 'BT-71',
                'type' => 'identifier',
                'min' => 1,
                'multiple' => false,
                'description' => 'Ein Bezeichner für den Ort, an den die Waren geliefert oder an dem die Dienstleistungen erbracht werden.',
            ],
            'Actual_delivery_date' => [
                'id' => 'BT-72',
                'type' => 'date',
                'min' => 1,
                'multiple' => false,
                'description' => 'Datum, an dem die Lieferung tatsächlich erfolgt bzw. die Dienstleistung tatsächlich erbracht wird.',
            ],
            'DELIVER_TO_ADDRESS' => [
                'id' => 'BG-15',
                'type' => 'DELIVER_TO_ADDRESSType',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine Gruppe von Informationselementen, die Informationen über die Anschrift liefern, an die die Waren geliefert oder an der die Dienstleistungen erbracht werden. Die Gruppe ist nur zu verwenden, wenn die Lieferanschrift von der Erwerberanschrift abweicht. Wenn die Waren abgeholt werden, ist die Abholadresse die Lieferadresse. Eine vollständige gültige Anschrift ist anzugeben.',
            ],
        ],
        'INVOICING_PERIODType' => [
            'Invoicing_period_start_date' => [
                'id' => 'BT-73',
                'type' => 'date',
                'min' => 1,
                'multiple' => false,
                'description' => 'Das Datum, an dem der Rechnungszeitraum beginnt.',
            ],
            'Invoicing_period_end_date' => [
                'id' => 'BT-74',
                'type' => 'date',
                'min' => 1,
                'multiple' => false,
                'description' => 'Das Datum, an dem der Rechnungszeitraum endet.',
            ],
        ],
        'DELIVER_TO_ADDRESSType' => [
            'Deliver_to_address_line_1' => [
                'id' => 'BT-75',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Die Hauptzeile einer Anschrift. Üblicherweise ist dies entweder Strasse und Hausnummer oder der Text "Postfach" gefolgt von der Postfachnummer.',
            ],
            'Deliver_to_address_line_2' => [
                'id' => 'BT-76',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine zusätzliche Adresszeile in einer Anschrift, die verwendet werden kann, um weitere Einzelheiten in Ergänzung zur Hauptzeile anzugeben.',
            ],
            'Deliver_to_address_line_3' => [
                'id' => 'BT-165',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine zusätzliche Adresszeile in einer Anschrift, die verwendet werden kann, um weitere Einzelheiten in Ergänzung zur Hauptzeile anzugeben.',
            ],
            'Deliver_to_city' => [
                'id' => 'BT-77',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Die Bezeichnung der Stadt oder Gemeinde, in der sich die Erwerberanschrift befindet.',
            ],
            'Deliver_to_post_code' => [
                'id' => 'BT-78',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Der Bezeichner für eine dem zuständigen Postdienst entsprechend adressierbare Gruppe von Eigenschaften.',
            ],
            'Deliver_to_country_subdivision' => [
                'id' => 'BT-79',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Die Unterteilung eines Landes (wie Region, Bundesland, Provinz etc.).',
            ],
            'Deliver_to_country_code' => [
                'id' => 'BT-80',
                'type' => 'code',
                'min' => 1,
                'multiple' => false,
                'description' => 'Ein Code, mit dem das Land bezeichnet wird. Anmerkung: Die Liste der zulässigen Länder ist bei der ISO 3166-1 «Codes for the representation of names of countries and their subdivisions» erhältlich. Nur die Alpha-2-Darstellung darf verwendet werden.',
            ],
        ],
        'PAYMENT_INSTRUCTIONSType' => [
            'Payment_means_type_code' => [
                'id' => 'BT-81',
                'type' => 'code',
                'min' => 1,
                'multiple' => false,
                'description' => 'Das als Code ausgedrückte erwartete oder genutzte Zahlungsmittel. Hierzu wird auf die Codeliste UN/ECE 4461 verwiesen.',
            ],
            'Payment_means_text' => [
                'id' => 'BT-82',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Das in Textform ausgedrückte erwartete oder genutzte Zahlungsmittel.',
            ],
            'Remittance_information' => [
                'id' => 'BT-83',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Ein Textwert, der zur Verknüpfung der Zahlung mit der vom Verkäufer ausgestellten Rechnung verwendet wird. Anmerkung: Die Angabe eines Verwendungszwecks hilft dem Verkäufer bei der Zuweisung einer eingehenden Zahlung zum jeweiligen Zahlungsprozess. Wenn Remittance information in der Rechnung übermittelt wurde, sollte diese daher bei der Zahlung genutzt werden.',
            ],
            'CREDIT_TRANSFER' => [
                'id' => 'BG-17',
                'type' => 'CREDIT_TRANSFERType',
                'min' => 1,
                'multiple' => true,
                'description' => 'Eine Gruppe von Informationselementen, die Informationen über das Bankkonto geben, auf das die Überweisung zu leisten ist. Die Gruppe ist alternativ zu PAYMENT_CARD_INFORMATION-BG-18; oder zu DIRECT_DEBIT-BG-19; anzugeben, wenn eine Zahlung per Überweisung erfolgen soll.',
            ],
            'PAYMENT_CARD_INFORMATION' => [
                'id' => 'BG-18',
                'type' => 'PAYMENT_CARD_INFORMATIONType',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine Gruppe von Informationselementen, die Informationen über die für die Zahlung genutzte Karte liefern. Die Gruppe ist alternativ zu DIRECT_DEBIT-BG-19; (Lastschrift mit Vorliegen einer Mandatsreferenz) oder zu CREDIT_TRANSFER-BG-17; (Überweisung) anzugeben, wenn eine Zahlung per Zahlungskarte/Kreditkarte erfolgte.',
            ],
            'DIRECT_DEBIT' => [
                'id' => 'BG-19',
                'type' => 'DIRECT_DEBITType',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine Gruppe von Informationselementen, die spezifische Informationen über die vorgesehene Lastschrift geben. Die Gruppe ist alternativ zu CREDIT_TRANSFER-BG-17; oder zu PAYMENT_CARD_INFORMATION-BG-18; anzugeben, wenn ein Mandat erteilt wurde und der Rechnungsbetrag per Lastschrift beglichen werden soll.',
            ],
        ],
        'CREDIT_TRANSFERType' => [
            'Payment_account_identifier' => [
                'id' => 'BT-84',
                'type' => 'identifier',
                'min' => 1,
                'multiple' => false,
                'description' => 'Die Kennung des Kontos, auf das die Zahlung erfolgen soll: IBAN für Zahlungen im SEPA-Raum, Kontonummer oder IBAN im Falle von Auslandszahlungen.',
            ],
            'Payment_account_name' => [
                'id' => 'BT-85',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Name des Kontos bei einem Zahlungsdienstleister, auf das die Zahlung erfolgen soll. (z. B. Kontoinhaber)',
            ],
            'Payment_service_provider_identifier' => [
                'id' => 'BT-86',
                'type' => 'identifier',
                'min' => 1,
                'multiple' => false,
                'description' => 'Die Kennung des Konto führenden Kreditinstitutes, ergibt sich bei Zahlungen im SEPA-Raum im Regelfall aus IBAN; für Auslandszahlungen, bei denen um BIC ergänzt werden muss: für alle Zahlungen an Bankverbindungen des SEPA-Raumes als SCT (Code 58 des Payment_means_type_code-BT-81;) oder SDD (Code 59 des Payment_means_type_code-BT-81;) mit Ausnahme der nachstehenden Ausnahmen, reicht die Angabe der IBAN, die in der Länge variiert; BIC nicht erforderlich. Ausnahmen: z. B. San Marino, Monaco, Schweiz, Saint Pierre und Miquelon, wobei die Länge der IBAN variiert, aber immer 1. und 2. Stelle = Ländercode nach ISO, 3. und 4. Stelle = Prüfziffer; Angabe des BIC ist neben der Angabe der IBAN zwingend erforderlich für alle Zahlungen an Bankverbindungen außerhalb des SEPA-Raumes (Code 30 (Credit transfer (non-SEPA)) bzw. (Code 49 Direct debit (non-SEPA)) des Payment_means_type_code-BT-81;) sind, abhängig vom empfangenden Institut, IBAN bzw. Kontonummer und BIC nötig',
            ],
        ],
        'PAYMENT_CARD_INFORMATIONType' => [
            'Payment_card_primary_account_number' => [
                'id' => 'BT-87',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Die Nummer der Kreditkarte, die für die Zahlung genutzt wurde. Anmerkung: In Übereinstimmung mit den für Kreditkarten geltenden Sicherheitsstandards darf eine Rechnung nicht die vollständige Kartennummer enthalten.',
            ],
            'Payment_card_holder_name' => [
                'id' => 'BT-88',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Name des Karteninhabers.',
            ],
        ],
        'DIRECT_DEBITType' => [
            'Mandate_reference_identifier' => [
                'id' => 'BT-89',
                'type' => 'identifier',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eindeutige Kennung, die vom Zahlungsempfänger zur Referenzierung der Einzugsermächtigung zugewiesen wird (Mandatsreferenznummer).',
            ],
            'Bank_assigned_creditor_identifier' => [
                'id' => 'BT-90',
                'type' => 'identifier',
                'min' => 1,
                'multiple' => false,
                'description' => 'Die eindeutige Kennung des Verkäufers (Seller) oder des Zahlungsempfängers (Payee), um am SEPA-Lastschriftverfahren teilnehmen zu können (Gläubiger-ID).',
            ],
            'Debited_account_identifier' => [
                'id' => 'BT-91',
                'type' => 'identifier',
                'min' => 1,
                'multiple' => false,
                'description' => 'Die Kennung des Kontos, von dem die Lastschrift erfolgen soll: IBAN für Zahlungen im SEPA-Raum, Kontonummer oder IBAN im Falle von Auslandszahlungen.',
            ],
        ],
        'DOCUMENT_LEVEL_ALLOWANCESType' => [
            'Document_level_allowance_amount' => [
                'id' => 'BT-92',
                'type' => 'amount',
                'min' => 1,
                'multiple' => false,
                'description' => 'Der Nachlassbetrag ohne Umsatzsteuer.',
            ],
            'Document_level_allowance_base_amount' => [
                'id' => 'BT-93',
                'type' => 'amount',
                'min' => 1,
                'multiple' => false,
                'description' => 'Der Grundbetrag, der in Verbindung mit dem Prozentsatz des Nachlasses auf der Dokumentenebene zur Berechnung des Betrags des Nachlasses auf der Dokumentenebene verwendet werden kann.',
            ],
            'Document_level_allowance_percentage' => [
                'id' => 'BT-94',
                'type' => 'percentage',
                'min' => 1,
                'multiple' => false,
                'description' => 'Der Prozentsatz, der in Verbindung mit dem Grundbetrag des Nachlasses auf der Dokumentenebene zur Berechnung des Betrags des Nachlasses auf der Dokumentenebene verwendet werden kann.',
            ],
            'Document_level_allowance_VAT_category_code' => [
                'id' => 'BT-95',
                'type' => 'code',
                'min' => 1,
                'multiple' => false,
                'description' => 'Ein Code für das Umsatzsteuermerkmal, das auf den Nachlass auf Dokumentenebene anzuwenden ist. Anmerkung: Folgende Codes aus der Codeliste UNTDID 5305 müssen verwendet werden: S (Standard rate) Z (Zero rated goods) E (Exempt from tax) AE (VAT Reverse Charge) K (VAT exempt for EEA intra-community supply of goods and services) G (Free export item, tax not charged) O (Services outside scope of tax) L (Canary Islands general indirect tax) M (Tax for production, services and importation in Ceuta and Melilla)',
            ],
            'Document_level_allowance_VAT_rate' => [
                'id' => 'BT-96',
                'type' => 'percentage',
                'min' => 1,
                'multiple' => false,
                'description' => 'Der für den Nachlass auf der Dokumentenebene geltende und in Prozent angegebene Umsatzsteuersatz.',
            ],
            'Document_level_allowance_reason' => [
                'id' => 'BT-97',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Der in Textform angegebene Grund für den Nachlass auf der Dokumentenebene.',
            ],
            'Document_level_allowance_reason_code' => [
                'id' => 'BT-98',
                'type' => 'code',
                'min' => 1,
                'multiple' => false,
                'description' => 'Der als Code angegebene Grund für den Nachlass auf der Dokumentenebene. Anmerkung: Hier sind die Codes aus der Codeliste UNTDID 5189 zu verwenden. Dabei müssen Document level allowance reason code und Document level allowance reason text den gleichen Grund für den Nachlass angeben.',
            ],
        ],
        'DOCUMENT_LEVEL_CHARGESType' => [
            'Document_level_charge_amount' => [
                'id' => 'BT-99',
                'type' => 'amount',
                'min' => 1,
                'multiple' => false,
                'description' => 'Der Betrag einer Abgabe ohne die Umsatzsteuer.',
            ],
            'Document_level_charge_base_amount' => [
                'id' => 'BT-100',
                'type' => 'amount',
                'min' => 1,
                'multiple' => false,
                'description' => 'Der Grundbetrag, der in Verbindung mit dem Prozentsatz der Abgaben auf der Dokumentenebene zur Berechnung des Betrags der Abgaben auf der Dokumentenebene verwendet werden kann (Bemessungsgrundlage).',
            ],
            'Document_level_charge_percentage' => [
                'id' => 'BT-101',
                'type' => 'percentage',
                'min' => 1,
                'multiple' => false,
                'description' => 'Der Prozentsatz, der in Verbindung mit dem Grundbetrag der Abgaben auf der Dokumentenebene zur Berechnung des Betrags der Abgaben auf der Dokumentenebene verwendet werden kann.',
            ],
            'Document_level_charge_VAT_category_code' => [
                'id' => 'BT-102',
                'type' => 'code',
                'min' => 1,
                'multiple' => false,
                'description' => 'Ein Code für das Umsatzsteuermerkmal dieser Elementgruppe. Anmerkung: Folgende Codes aus der Codeliste UNTDID 5305 müssen verwendet werden: S (Standard rate) Z (Zero rated goods) E (Exempt from tax) AE (VAT Reverse Charge) K (VAT exempt for EEA intra-community supply of goods and services) G (Free export item, tax not charged) O (Services outside scope of tax) L (Canary Islands general indirect tax) M (Tax for production, services and importation in Ceuta and Melilla)',
            ],
            'Document_level_charge_VAT_rate' => [
                'id' => 'BT-103',
                'type' => 'percentage',
                'min' => 1,
                'multiple' => false,
                'description' => 'Der Umsatzsteuersatz, dargestellt als Prozentsatz, der für die Abgaben auf der Dokumentenebene gilt.',
            ],
            'Document_level_charge_reason' => [
                'id' => 'BT-104',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Der in Textform angegebene Grund für die Abgaben auf der Dokumentenebene.',
            ],
            'Document_level_charge_reason_code' => [
                'id' => 'BT-105',
                'type' => 'code',
                'min' => 1,
                'multiple' => false,
                'description' => 'Der als Code angegebene Grund für die Abgaben auf der Dokumentenebene. Anmerkung: Hier sind die Codes aus der Codeliste UNTDID 7161 zu verwenden. Document level charge reason code und Document level charge reason müssen auf den gleichen Grund für die Abgaben auf Dokumentenebene verweisen.',
            ],
        ],
        'DOCUMENT_TOTALSType' => [
            'Sum_of_Invoice_line_net_amount' => [
                'id' => 'BT-106',
                'type' => 'amount',
                'min' => 1,
                'multiple' => false,
                'description' => 'Summe aller Rechnungspositionen-Nettobeträge der Rechnung.',
            ],
            'Sum_of_allowances_on_document_level' => [
                'id' => 'BT-107',
                'type' => 'amount',
                'min' => 1,
                'multiple' => false,
                'description' => 'Summe aller in der Rechnung enthaltenen Nachlässe der Dokumentenebene.',
            ],
            'Sum_of_charges_on_document_level' => [
                'id' => 'BT-108',
                'type' => 'amount',
                'min' => 1,
                'multiple' => false,
                'description' => 'Summe aller in der Rechnung enthaltenen Abgaben der Dokumentenebene.',
            ],
            'Invoice_total_amount_without_VAT' => [
                'id' => 'BT-109',
                'type' => 'amount',
                'min' => 1,
                'multiple' => false,
                'description' => 'Der Gesamtbetrag der Rechnung ohne Umsatzsteuer.',
            ],
            'Invoice_total_VAT_amount' => [
                'id' => 'BT-110',
                'type' => 'amount',
                'min' => 1,
                'multiple' => false,
                'description' => 'Der Gesamtbetrag der Umsatzsteuer für die Rechnung.',
            ],
            'Invoice_total_VAT_amount_in_accounting_currency' => [
                'id' => 'BT-111',
                'type' => 'amount',
                'min' => 1,
                'multiple' => false,
                'description' => 'Der Umsatzsteuergesamtbetrag, angegeben in der Abrechnungswährung, die im Land des Verkäufers gültig ist oder verlangt wird.',
            ],
            'Invoice_total_amount_with_VAT' => [
                'id' => 'BT-112',
                'type' => 'amount',
                'min' => 1,
                'multiple' => false,
                'description' => 'Der Gesamtbetrag der Rechnung mit Umsatzsteuer.',
            ],
            'Paid_amount' => [
                'id' => 'BT-113',
                'type' => 'amount',
                'min' => 1,
                'multiple' => false,
                'description' => 'Summe bereits gezahlter Beträge.',
            ],
            'Rounding_amount' => [
                'id' => 'BT-114',
                'type' => 'amount',
                'min' => 1,
                'multiple' => false,
                'description' => 'Der Betrag, um den der Rechnungsbetrag gerundet wurde.',
            ],
            'Amount_due_for_payment' => [
                'id' => 'BT-115',
                'type' => 'amount',
                'min' => 1,
                'multiple' => false,
                'description' => 'Der ausstehende Betrag. Dies ist der Rechnungsbetrag inkl. Umsatzsteuer abzüglich des bereits gezahlten Betrags. Dieser Betrag ist der Rechnungsgesamtbetrag einschließlich Umsatzsteuer abzüglich der Summe bereits gezahlter Beträge. Im Falle einer vollständig beglichenen Rechnung ist dieser Betrag gleich null. Der Betrag ist negativ, falls der gezahlte Betrag größer als der Rechnungsgesamtbetrag einschließlich Umsatzsteuer ist.',
            ],
        ],
        'VAT_BREAKDOWNType' => [
            'VAT_category_taxable_amount' => [
                'id' => 'BT-116',
                'type' => 'amount',
                'min' => 1,
                'multiple' => false,
                'description' => 'Summe aller zu versteuernden Beträge, für die ein bestimmter Code der Umsatzsteuerkategorie und ein bestimmter Umsatzsteuersatz gelten (falls ein kategoriespezifischer Umsatzsteuersatz gilt).',
            ],
            'VAT_category_tax_amount' => [
                'id' => 'BT-117',
                'type' => 'amount',
                'min' => 1,
                'multiple' => false,
                'description' => 'Der für die betreffende Umsatzsteuerkategorie zu entrichtende Gesamtbetrag. Anmerkung: Die Berechnung erfolgt durch Multiplikation des VAT category taxable amount mit der VAT category rate der jeweiligen VAT category.',
            ],
            'VAT_category_code' => [
                'id' => 'BT-118',
                'type' => 'code',
                'min' => 1,
                'multiple' => false,
                'description' => 'Codierte Bezeichnung einer Umsatzsteuerkategorie. Anmerkung: Folgende Codes aus der Codeliste UNTDID 5305 müssen verwendet werden: S (Standard rate) Z (Zero rated goods) E (Exempt from tax) AE (VAT Reverse Charge) K (VAT exempt for EEA intra-community supply of goods and services) G (Free export item, tax not charged) O (Services outside scope of tax) L (Canary Islands general indirect tax) M (Tax for production, services and importation in Ceuta and Melilla)',
            ],
            'VAT_category_rate' => [
                'id' => 'BT-119',
                'type' => 'percentage',
                'min' => 1,
                'multiple' => false,
                'description' => 'Der Umsatzsteuersatz, angegeben als für die betreffende Umsatzsteuerkategorie geltender Prozentsatz.',
            ],
            'VAT_exemption_reason_text' => [
                'id' => 'BT-120',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'In Textform angegebener Grund für die Ausnahme des Betrages von der Umsatzsteuerpflicht. Sofern die Umsatzsteuerkategorie «AE» für die Rechnung gilt, ist hier der Text «Umkehrung der Steuerschuldnerschaft» oder der entsprechende Normtext in der für die Rechnung gewählten Sprache anzugeben.',
            ],
            'VAT_exemption_reason_code' => [
                'id' => 'BT-121',
                'type' => 'code',
                'min' => 1,
                'multiple' => false,
                'description' => 'Ein Code für den Grund für die Ausnahme des Betrages von der Umsatzsteuerpflicht. Die Codeliste «VAT exemption reason code list (VATEX)» wird von der Connecting Europe Facility gepflegt und herausgegeben.',
            ],
        ],
        'ADDITIONAL_SUPPORTING_DOCUMENTSType' => [
            'Supporting_document_reference' => [
                'id' => 'BT-122',
                'type' => 'document_reference',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine Kennung der rechnungsbegründenden Unterlage.',
            ],
            'Supporting_document_description' => [
                'id' => 'BT-123',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine Beschreibung der rechnungsbegründenden Unterlage.',
            ],
            'External_document_location' => [
                'id' => 'BT-124',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Die Internetadresse bzw. URL (Uniform Resource Locator), unter der das externe Dokument verfügbar ist.',
            ],
            'Attached_document' => [
                'id' => 'BT-125',
                'type' => 'binary_object',
                'min' => 1,
                'multiple' => false,
                'description' => 'Ein als Binärobjekt eingebettetes Anhangsdokument.',
            ],
        ],
        'INVOICE_LINEType' => [
            'Invoice_line_identifier' => [
                'id' => 'BT-126',
                'type' => 'identifier',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eindeutige Bezeichnung für die betreffende Rechnungsposition.',
            ],
            'Invoice_line_note' => [
                'id' => 'BT-127',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Ein Textvermerk, der unstrukturierte Informationen enthält, die für die Rechnungsposition maßgeblich sind.',
            ],
            'Invoice_line_object_identifier' => [
                'id' => 'BT-128',
                'type' => 'identifier',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine vom Verkäufer angegebene Kennung für ein Objekt, auf das sich die Rechnungsposition bezieht (z. B. Zählernummer, Telefonnummer, Kfz-Kennzeichen, versicherte Person, Abonnement-Nummer, Rufnummer).',
            ],
            'Invoiced_quantity' => [
                'id' => 'BT-129',
                'type' => 'quantity',
                'min' => 1,
                'multiple' => false,
                'description' => 'Die Menge zu dem in der betreffenden Zeile in Rechnung gestellten Einzelposten (Waren oder Dienstleistungen).',
            ],
            'Invoiced_quantity_unit_of_measure_code' => [
                'id' => 'BT-130',
                'type' => 'code',
                'min' => 1,
                'multiple' => false,
                'description' => 'Die für die in Rechnung gestellte Menge geltende Maßeinheit. Die Maßeinheit muss unter Anwendung der in UN/ECE Rec No 20 Intro 2.a) beschriebenen Methode aus den Listen UN/ECE Recommendation No. 20 «Codes for Units of Measure Used in International Trade» und UN/ECE Recommendation No 21 «Codes for Passengers, Types of Cargo, Packages and Packaging Materials (with Complementary Codes for Package Names)» ausgewählt werden. In den meisten Fällen ist es nicht erforderlich, dass Verkäufer und Erwerber diese Listen vollständig in ihren Anwendungen implementieren. Verkäufer müssen nur die erforderlichen Einheiten für ihre Güter und Dienstleistungen unterstützen. Erwerber überprüfen lediglich, ob die in der Rechnung verwendeten Einheiten mit denen in anderen Dokumenten zum Erwerb (wie z. B. Vertrag, Katalog, Bestellung oder Lieferschein) identisch sind.',
            ],
            'Invoice_line_net_amount' => [
                'id' => 'BT-131',
                'type' => 'amount',
                'min' => 1,
                'multiple' => false,
                'description' => 'Der Gesamtbetrag der Rechnungsposition. Dies ist der Betrag ohne Umsatzsteuer, aber einschließlich aller für die Rechnungsposition geltenden Nachlässe und Abgaben sowie sonstiger anfallender Steuern.',
            ],
            'Referenced_purchase_order_line_reference' => [
                'id' => 'BT-132',
                'type' => 'document_reference',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine vom Erwerber ausgegebene Kennung für eine referenzierte Position einer Bestellung/eines Auftrags. Anmerkung: Auf den Auftrag wird auf Rechnungsebene Bezug genommen.',
            ],
            'Invoice_line_Buyer_accounting_reference' => [
                'id' => 'BT-133',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Ein Textwert, der angibt, an welcher Stelle die betreffenden Daten in den Finanzkonten des Erwerbers zu buchen sind. Anmerkung: Wenn die Angabe genutzt werden soll, muss der Erwerber dem Verkäufer diese Referenz vor der Rechnungserstellung mitteilen.',
            ],
            'INVOICE_LINE_PERIOD' => [
                'id' => 'BG-26',
                'type' => 'INVOICE_LINE_PERIODType',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine Gruppe von Informationselementen, die Informationen über den für die Rechnungsposition maßgeblichen Rechnungszeitraum liefern.',
            ],
            'INVOICE_LINE_ALLOWANCES' => [
                'id' => 'BG-27',
                'type' => 'INVOICE_LINE_ALLOWANCESType',
                'min' => 1,
                'multiple' => true,
                'description' => 'Eine Gruppe von Informationselementen, die Informationen über die für die betreffende Rechnungsposition geltenden Nachlässe liefern.',
            ],
            'INVOICE_LINE_CHARGES' => [
                'id' => 'BG-28',
                'type' => 'INVOICE_LINE_CHARGESType',
                'min' => 1,
                'multiple' => true,
                'description' => 'Eine Gruppe von Informationselementen, die Informationen über Kosten, Zuschläge, und Steuern ndash; ausgenommen die Umsatzsteuer ndash; enthalten, die für die jeweilige Rechnungsposition gelten. Anmerkung: Es wird davon ausgegangen, dass alle Kosten und Zuschläge dem gleichen Umsatzsteuersatz unterliegen wie die Rechnungsposition.',
            ],
            'PRICE_DETAILS' => [
                'id' => 'BG-29',
                'type' => 'PRICE_DETAILSType',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine Gruppe von Informationselementen, die Informationen über den Preis für die in der betreffenden Rechnungsposition in Rechnung gestellten Waren und Dienstleistungen liefern.',
            ],
            'LINE_VAT_INFORMATION' => [
                'id' => 'BG-30',
                'type' => 'LINE_VAT_INFORMATIONType',
                'min' => 1,
                'multiple' => true,
                'description' => 'Eine Gruppe von Informationselementen, die Informationen über die Umsatzsteuer liefern, die für die in der betreffenden Zeile in Rechnung gestellten Waren und Dienstleistungen gilt.',
            ],
            'ITEM_INFORMATION' => [
                'id' => 'BG-31',
                'type' => 'ITEM_INFORMATIONType',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine Gruppe von Informationselementen, die Informationen über die in Rechnung gestellten Waren und Dienstleistungen liefern.',
            ],
            'SUB_INVOICE_LINE' => [
                'id' => 'BG-DEX-01',
                'type' => 'INVOICE_LINEType',
                'min' => 1,
                'multiple' => true,
                'description' => 'Eine Gruppe von Informationselementen, die Informationen über einzelne Rechnungspositionen liefern.',
            ],
        ],
        'INVOICE_LINE_PERIODType' => [
            'Invoice_line_period_start_date' => [
                'id' => 'BT-134',
                'type' => 'date',
                'min' => 1,
                'multiple' => false,
                'description' => 'Das Datum, an dem der Rechnungszeitraum der betreffenden Rechnungsposition beginnt.',
            ],
            'Invoice_line_period_end_date' => [
                'id' => 'BT-135',
                'type' => 'date',
                'min' => 1,
                'multiple' => false,
                'description' => 'Das Datum, an dem der Rechnungszeitraum der betreffenden Rechnungsposition endet.',
            ],
        ],
        'INVOICE_LINE_ALLOWANCESType' => [
            'Invoice_line_allowance_amount' => [
                'id' => 'BT-136',
                'type' => 'amount',
                'min' => 1,
                'multiple' => false,
                'description' => 'Der Nachlassbetrag ohne Umsatzsteuer.',
            ],
            'Invoice_line_allowance_base_amount' => [
                'id' => 'BT-137',
                'type' => 'amount',
                'min' => 1,
                'multiple' => false,
                'description' => 'Der Grundbetrag, der in Verbindung mit dem prozentualen Rechnungspositionennachlass zur Berechnung des Betrags des Rechnungspositionennachlasses verwendet werden kann.',
            ],
            'Invoice_line_allowance_percentage' => [
                'id' => 'BT-138',
                'type' => 'percentage',
                'min' => 1,
                'multiple' => false,
                'description' => 'Der Prozentsatz, der in Verbindung mit dem Grundbetrag des Rechnungspositionennachlasses zur Berechnung des Betrags des Rechnungspositionennachlasses verwendet werden kann.',
            ],
            'Invoice_line_allowance_reason' => [
                'id' => 'BT-139',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Der in Textform angegebene Grund für den Rechnungspositionennachlass.',
            ],
            'Invoice_line_allowance_reason_code' => [
                'id' => 'BT-140',
                'type' => 'code',
                'min' => 1,
                'multiple' => false,
                'description' => 'Der als Code angegebene Grund für den Rechnungspositionennachlass. Anmerkung: Hier sind die Codes aus der Codeliste UNTDID 5189 zu verwenden. Invoice line level allowance reason code und Invoice line level allowance reason müssen den gleichen Nachlassgrund angeben.',
            ],
        ],
        'INVOICE_LINE_CHARGESType' => [
            'Invoice_line_charge_amount' => [
                'id' => 'BT-141',
                'type' => 'amount',
                'min' => 1,
                'multiple' => false,
                'description' => 'Der Betrag einer Abgabe ohne die Umsatzsteuer.',
            ],
            'Invoice_line_charge_base_amount' => [
                'id' => 'BT-142',
                'type' => 'amount',
                'min' => 1,
                'multiple' => false,
                'description' => 'Der Grundbetrag, der in Verbindung mit den prozentualen Rechnungspositionenabgaben zur Berechnung des Betrags der Rechnungspositionenabgaben verwendet werden kann.',
            ],
            'Invoice_line_charge_percentage' => [
                'id' => 'BT-143',
                'type' => 'percentage',
                'min' => 1,
                'multiple' => false,
                'description' => 'Der Prozentsatz, der in Verbindung mit dem Grundbetrag der Rechnungspositionenabgaben zur Berechnung des Betrags der Rechnungspositionenabgaben verwendet werden kann.',
            ],
            'Invoice_line_charge_reason' => [
                'id' => 'BT-144',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Der in Textform angegebene Grund für die Rechnungspositionenabgaben.',
            ],
            'Invoice_line_charge_reason_code' => [
                'id' => 'BT-145',
                'type' => 'code',
                'min' => 1,
                'multiple' => false,
                'description' => 'Der als Code angegebene Grund für die Rechnungspositionenabgaben. Anmerkung: Hier sind die Codes aus der Codeliste UNTDID 7161 zu verwenden. Invoice line charge reason code und Invoice line charge reason müssen auf den gleichen Grund für die Abgaben auf die Rechnungsposition verweisen.',
            ],
        ],
        'PRICE_DETAILSType' => [
            'Item_net_price' => [
                'id' => 'BT-146',
                'type' => 'unit_price_amount',
                'min' => 1,
                'multiple' => false,
                'description' => 'Der Preis eines Postens, ohne Umsatzsteuer, nach Abzug des für diese Rechnungsposition geltenden Rabatts. Anmerkung: Item net price muss gleich Item gross price abzüglich Item price discount sein.',
            ],
            'Item_price_discount' => [
                'id' => 'BT-147',
                'type' => 'unit_price_amount',
                'min' => 1,
                'multiple' => false,
                'description' => 'Der gesamte zur Berechnung des Netto-Postenpreises vom Brutto-Postenpreis subtrahierte Rabatt. Anmerkung: Nur anzugeben, wenn der Nachlass pro Verpackungseinheit gegeben wird und nicht in den Item gross price inkludiert ist.',
            ],
            'Item_gross_price' => [
                'id' => 'BT-148',
                'type' => 'unit_price_amount',
                'min' => 1,
                'multiple' => false,
                'description' => 'Der Postenpreis ohne Umsatzsteuer vor Abzug des Postenpreisrabatts.',
            ],
            'Item_price_base_quantity' => [
                'id' => 'BT-149',
                'type' => 'quantity',
                'min' => 1,
                'multiple' => false,
                'description' => 'Die Anzahl von Einheiten, für die der Postenpreis gilt.',
            ],
            'Item_price_base_quantity_unit_of_measure' => [
                'id' => 'BT-150',
                'type' => 'code',
                'min' => 1,
                'multiple' => false,
                'description' => 'Der Code der zu Grunde gelegten Maßeinheit. Die Maßeinheit der Item price base quantity unit of measure sollte gleich der Maßeinheit der in Rechnung gestellten Menge (BT-130) sein.',
            ],
        ],
        'LINE_VAT_INFORMATIONType' => [
            'Invoiced_item_VAT_category_code' => [
                'id' => 'BT-151',
                'type' => 'code',
                'min' => 1,
                'multiple' => false,
                'description' => 'Der Code der für den in Rechnung gestellten Posten geltenden Umsatzsteuerkategorie. Anmerkung: Folgende Codes aus der Codeliste UNTDID 5305 müssen verwendet werden: S (Standard rate) Z (Zero rated goods) E (Exempt from tax) AE (VAT Reverse Charge) K (VAT exempt for EEA intra-community supply of goods and services) G (Free export item, tax not charged) O (Services outside scope of tax) L (Canary Islands general indirect tax) M (Tax for production, services and importation in Ceuta and Melilla)',
            ],
            'Invoiced_item_VAT_rate' => [
                'id' => 'BT-152',
                'type' => 'percentage',
                'min' => 1,
                'multiple' => false,
                'description' => 'Der für den in Rechnung gestellten Posten geltende und als Prozentsatz angegebene Umsatzsteuersatz. Anmerkung: Ein Umsatzsteuersatz von 0 Prozent wird für Kalkulationszwecke auch dann angewandt, wenn der Posten außerhalb der Reichweite der Umsatzsteuer ist.',
            ],
        ],
        'ITEM_INFORMATIONType' => [
            'Item_name' => [
                'id' => 'BT-153',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Ein Name des Postens.',
            ],
            'Item_description' => [
                'id' => 'BT-154',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine Beschreibung des Postens. Anmerkung: Hier kann der Posten detaillierter beschrieben werden als im Namen.',
            ],
            'Item_Sellers_identifier' => [
                'id' => 'BT-155',
                'type' => 'identifier',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine dem Posten vom Verkäufer zugewiesene Kennung.',
            ],
            'Item_Buyers_identifier' => [
                'id' => 'BT-156',
                'type' => 'identifier',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine dem Posten vom Erwerber zugewiesene Kennung.',
            ],
            'Item_standard_identifier' => [
                'id' => 'BT-157',
                'type' => 'identifier',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine auf einem registrierten Schema basierende Postenkennung.',
            ],
            'Item_classification_identifier' => [
                'id' => 'BT-158',
                'type' => 'identifier',
                'min' => 1,
                'multiple' => true,
                'description' => 'Ein Code für die Klassifizierung des Postens nach Typ bzw. Art oder Wesen bzw. Beschaffenheit. Anmerkung: Klassifizierungscodes werden verwendet, um die Zusammenfassung gleichartiger Posten für unterschiedliche Zwecke zu ermöglichen.',
            ],
            'Item_country_of_origin' => [
                'id' => 'BT-159',
                'type' => 'code',
                'min' => 1,
                'multiple' => false,
                'description' => 'Der Ländercode, der das Land angibt, aus dem die Ware stammt oder in dem die Dienstleistung erbracht wird. Anmerkung: Die Liste der zulässigen Länder ist bei der ISO 3166-1 «Codes for the representation of names of countries and their subdivisions» erhältlich. Nur die Alpha-2-Darstellung darf verwendet werden.',
            ],
            'ITEM_ATTRIBUTES' => [
                'id' => 'BG-32',
                'type' => 'ITEM_ATTRIBUTESType',
                'min' => 1,
                'multiple' => true,
                'description' => 'Eine Gruppe von Informationselementen, die Informationen über die Eigenschaften der in Rechnung gestellten Waren und Dienstleistungen liefern.',
            ],
        ],
        'ITEM_ATTRIBUTESType' => [
            'Item_attribute_name' => [
                'id' => 'BT-160',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Der Name der Eigenschaft des Postens, wie z. B. «Farbe».',
            ],
            'Item_attribute_value' => [
                'id' => 'BT-161',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Der Wert der Eigenschaft des Postens, wie z. B. «rot».',
            ],
        ],
        'THIRD_PARTY_PAYMENTType' => [
            'Third_party_payment_type' => [
                'id' => 'BT-DEX-001',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Die Art der Fremdforderung.',
            ],
            'Third_party_payment_amount' => [
                'id' => 'BT-DEX-002',
                'type' => 'amount',
                'min' => 1,
                'multiple' => false,
                'description' => 'Der Betrag der Fremdforderung.',
            ],
            'Third_party_payment_description' => [
                'id' => 'BT-DEX-003',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine innerhalb der Rechnung eindeutige Beschreibung der Fremdforderung.',
            ],
        ],
        'invoice' => [
            'Invoice_number' => [
                'id' => 'BT-1',
                'type' => 'identifier',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine eindeutige Kennung der Rechnung, die diese im System des Verkäufers identifiziert. Anmerkung: Es ist kein «identification scheme» zu verwenden.',
            ],
            'Invoice_issue_date' => [
                'id' => 'BT-2',
                'type' => 'date',
                'min' => 1,
                'multiple' => false,
                'description' => 'Das Datum, an dem die Rechnung ausgestellt wurde.',
            ],
            'Invoice_type_code' => [
                'id' => 'BT-3',
                'type' => 'code',
                'min' => 1,
                'multiple' => false,
                'description' => 'Ein Code, der den Funktionstyp der Rechnung angibt. Anmerkung: Der Rechnungstyp muss gemäß UNTDID 1001 spezifiziert werden. Folgende Codes aus der Codeliste sollen verwendet werden: 326 (Partial invoice) 380 (Commercial invoice) 384 (Corrected invoice) 389 (Self-billed invoice) 381 (Credit note) 875 (Partial construction invoice) 876 (Partial final construction invoice) 877 (Final construction invoice)',
            ],
            'Invoice_currency_code' => [
                'id' => 'BT-5',
                'type' => 'code',
                'min' => 1,
                'multiple' => false,
                'description' => 'Die Währung, in der alle Rechnungsbeträge angegeben werden, ausgenommen ist der Umsatzsteuer-Gesamtbetrag, der in der Abrechnungswährung anzugeben ist. Anmerkung: Nur eine Währung ist in der Rechnung zu verwenden, der Invoice_total_VAT_amount_in_accounting_currency-BT-111; ist in der Abrechnungswährung auszuweisen. Die gültigen Währungen sind bei der ISO 4217 «Codes for the representation of currencies and funds» registriert. Nur die Alpha-3-Darstellung darf verwendet werden.',
            ],
            'VAT_accounting_currency_code' => [
                'id' => 'BT-6',
                'type' => 'code',
                'min' => 1,
                'multiple' => false,
                'description' => 'Die für die Umsatzsteuer-Abrechnungs- und -Meldezwecke verwendete Währung, die im Land des Verkäufers gültig ist oder verlangt wird. Anmerkung: Zu Verwenden in Kombination mit Invoice_total_VAT_amount_in_accounting_currency-BT-111;, wenn die Umsatzsteuerabrechnungswährung von der Rechnungswährung abweicht. Die gültigen Währungen sind bei der ISO 4217 «Codes for the representation of currencies and funds» registriert. Nur die Alpha-3-Darstellung darf verwendet werden.',
            ],
            'Value_added_tax_point_date' => [
                'id' => 'BT-7',
                'type' => 'date',
                'min' => 1,
                'multiple' => false,
                'description' => 'Das Datum, zu dem die Umsatzsteuer für den Verkäufer und für den Erwerber abrechnungsrelevant wird. Die Anwendung von BT-7 und 8 schließen sich gegenseitig aus.',
            ],
            'Value_added_tax_point_date_code' => [
                'id' => 'BT-8',
                'type' => 'code',
                'min' => 1,
                'multiple' => false,
                'description' => 'Ein Code für den Zeitpunkt, an dem die Umsatzsteuer für den Erwerber und den Verkäufer in der Buchführung nachzuweisen ist. Folgende Codes aus der Codeliste UNTDID 2005 werden verwendet: 3 (Invoice document issue date time) 35 (Delivery date/time, actual) 432 (Paid to date) Das Informationselement Value_added_tax_point_date_code-BT-8; wird verwendet, wenn das Informationselement Value_added_tax_point_date-BT-7; zum Zeitpunkt der Rechnungsstellung noch nicht bekannt ist. Die Anwendung von BT-7 und 8 schließen sich gegenseitig aus.',
            ],
            'Payment_due_date' => [
                'id' => 'BT-9',
                'type' => 'date',
                'min' => 1,
                'multiple' => false,
                'description' => 'Das Fälligkeitsdatum des Rechnungsbetrages.',
            ],
            'Buyer_reference' => [
                'id' => 'BT-10',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Ein vom Erwerber zugewiesener und für interne Lenkungszwecke benutzter Bezeichner. Anmerkung: Im Rahmen des Steuerungsprojekts eRechnung ist mit der so genannten Leitweg-ID eine Zuordnungsmöglichkeit entwickelt worden, deren verbindliche Nutzung von Bund und mehreren Ländern vorgegeben wird. Die Leitweg-ID ist prinzipiell für Bund, Länder und Kommunen einsetzbar. Für die Darstellung der Leitweg-ID wird das in XRechnung verpflichtende Feld Buyer Reference benutzt. Länder und Kommunen, die ihren Rechnungsstellern abweichend von der Leitweg-ID eigene Zuordnungsmuster mitteilen, können diese statt der Leitweg-ID im Feld Buyer Reference verwenden. Hinweis: Es existiert eine Handreichung zur Bildung der Leitweg-ID, die über die KoSIT zu erhalten ist (siehe Website XRechnung bzw. FAQ-Liste).',
            ],
            'Project_reference' => [
                'id' => 'BT-11',
                'type' => 'document_reference',
                'min' => 1,
                'multiple' => false,
                'description' => 'Die Kennung eines Projektes, auf das sich die Rechnung bezieht.',
            ],
            'Contract_reference' => [
                'id' => 'BT-12',
                'type' => 'document_reference',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine eindeutige Bezeichnung des Vertrages (z. B. Vertragsnummer).',
            ],
            'Purchase_order_reference' => [
                'id' => 'BT-13',
                'type' => 'document_reference',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine vom Erwerber ausgegebene Kennung für eine referenzierte Bestellung.',
            ],
            'Sales_order_reference' => [
                'id' => 'BT-14',
                'type' => 'document_reference',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine vom Verkäufer ausgegebene Kennung für einen referenzierten Auftrag.',
            ],
            'Receiving_advice_reference' => [
                'id' => 'BT-15',
                'type' => 'document_reference',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine Kennung für eine referenzierte Empfangsbestätigung.',
            ],
            'Despatch_advice_reference' => [
                'id' => 'BT-16',
                'type' => 'document_reference',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine Kennung für eine referenzierte Versandanzeige.',
            ],
            'Tender_or_lot_reference' => [
                'id' => 'BT-17',
                'type' => 'document_reference',
                'min' => 1,
                'multiple' => false,
                'description' => 'Die Kennung der Ausschreibung oder des Loses auf die/das sich die Rechnung bezieht.',
            ],
            'Invoiced_object_identifier' => [
                'id' => 'BT-18',
                'type' => 'identifier',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine vom Verkäufer angegebene Kennung für ein Objekt, auf das sich die Rechnung bezieht (z. B. Zählernummer, Telefonnummer, Kfz-Kennzeichen, versicherte Person, Abonnement-Nummer, Rufnummer).',
            ],
            'Buyer_accounting_reference' => [
                'id' => 'BT-19',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Ein Textwert, der angibt, an welcher Stelle die betreffenden Daten in den Finanzkonten des Erwerbers zu buchen sind.',
            ],
            'Payment_terms' => [
                'id' => 'BT-20',
                'type' => 'text',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine Textbeschreibung der Zahlungsbedingungen, die für den fälligen Zahlungsbetrag gelten (einschließlich Beschreibung möglicher Skontobedingungen). Dieses Informationselement kann mehrere Zeilen und mehrere Angaben zu Zahlungsbedingungen beinhalten und sowohl unstrukturierten als strukturierten Text enthalten. Der unstrukturierte Text darf dabei keine # enthalten. Werden Informationen zur Gewährung von Skonto angegeben, sind sie wie folgt darzustellen: Anzugeben ist im ersten Segment «SKONTO», im zweiten «TAGE=n», im dritten «PROZENT=n». Prozentzahlen sind ohne Vorzeichen sowie mit Punkt getrennt von zwei Nachkommastellen anzugeben. Liegt dem zu berechnenden Betrag nicht BT-115, «fälliger Betrag» zugrunde, sondern nur ein Teil des fälligen Betrags der Rechnung, ist der Grundwert zur Berechnung von Skonto als viertes Segment «BASISBETRAG=n» gemäß dem semantischen Datentypen Amount anzugeben. Jeder Eintrag beginnt mit einer #, die Segmente sind mit einer # getrennt und eine Zeile schließt mit einer # ab. Am Ende einer vollständigen Skontoangabe muss ein XML-konformer Zeilenumbruch folgen. Beispiele mit drei Segmenten je Zeile: #SKONTO#TAGE=14#PROZENT=2.25# #SKONTO#TAGE=28#PROZENT=1.00# Beispiele mit vier Segmenten je Zeile (die Gewährung von Skonto bezieht sich nur auf einen Teilbetrag der Rechnung (z. B. Material) und der Grundwert zur Berechnung des Skonto muss mit angegeben werden): #SKONTO#TAGE=14#PROZENT=2.25#BASISBETRAG=357.93# #SKONTO#TAGE=28#PROZENT=1.00#BASISBETRAG=357.93# Alle Angaben zur Gewährung von Skonto müssen in Großbuchstaben gemacht werden. Zusätzliches Whitespace (Leerzeichen, Tabulatoren oder Zeilenumbrüche) ist nicht zulässig. Andere Zeichen oder Texte als in den oberen Beispielen genannt sind nicht zulässig.',
            ],
            'INVOICE_NOTE' => [
                'id' => 'BG-1',
                'type' => 'INVOICE_NOTEType',
                'min' => 1,
                'multiple' => true,
                'description' => 'Eine Gruppe von Informationselementen für rechnungsrelevante Erläuterungen mit Hinweisen auf den Rechnungsbetreff.',
            ],
            'PROCESS_CONTROL' => [
                'id' => 'BG-2',
                'type' => 'PROCESS_CONTROLType',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine Gruppe von Informationselementen, die Informationen über den Geschäftsprozess und für die Rechnung geltende Regeln liefern.',
            ],
            'PRECEDING_INVOICE_REFERENCE' => [
                'id' => 'BG-3',
                'type' => 'PRECEDING_INVOICE_REFERENCEType',
                'min' => 1,
                'multiple' => true,
                'description' => 'Eine Gruppe von Informationselementen, die Informationen über eine vorausgegangene Rechnung liefern, die berichtigt oder gutgeschrieben werden soll. Anmerkung: Das Informationselement ist zu verwenden, wenn eine vorangegangene Rechnung korrigiert wird, eine Abschlussrechnung auf vorangegangene Teilrechnungen Bezug nimmt oder eine Abschlussrechnung auf vorangegangene Vorauszahlungsrechnungen Bezug nimmt.',
            ],
            'SELLER' => [
                'id' => 'BG-4',
                'type' => 'SELLERType',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine Gruppe von Informationselementen, die Informationen über den Verkäufer liefern.',
            ],
            'BUYER' => [
                'id' => 'BG-7',
                'type' => 'BUYERType',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine Gruppe von Informationselementen, die Informationen über den Erwerber liefern.',
            ],
            'PAYEE' => [
                'id' => 'BG-10',
                'type' => 'PAYEEType',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine Gruppe von Informationselementen, die Informationen über den Zahlungsempfänger liefern. Die Gruppe wird genutzt, wenn der Zahlungsempfänger nicht mit dem Verkäufer identisch ist.',
            ],
            'SELLER_TAX_REPRESENTATIVE_PARTY' => [
                'id' => 'BG-11',
                'type' => 'SELLER_TAX_REPRESENTATIVE_PARTYType',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine Gruppe von Informationselementen, die Informationen über den Steuervertreter des Verkäufers liefern.',
            ],
            'DELIVERY_INFORMATION' => [
                'id' => 'BG-13',
                'type' => 'DELIVERY_INFORMATIONType',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine Gruppe von Informationselementen, die Informationen darüber liefern, wo und wann die in Rechnung gestellten Waren und Dienstleistungen geliefert bzw. erbracht werden.',
            ],
            'INVOICING_PERIOD' => [
                'id' => 'BG-14',
                'type' => 'INVOICING_PERIODType',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine Gruppe von Informationselementen, die Informationen über den Rechnungszeitraum liefern.',
            ],
            'PAYMENT_INSTRUCTIONS' => [
                'id' => 'BG-16',
                'type' => 'PAYMENT_INSTRUCTIONSType',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine Gruppe von Informationselementen, die Informationen darüber liefern, wie die Zahlung erfolgen soll.',
            ],
            'DOCUMENT_LEVEL_ALLOWANCES' => [
                'id' => 'BG-20',
                'type' => 'DOCUMENT_LEVEL_ALLOWANCESType',
                'min' => 1,
                'multiple' => true,
                'description' => 'Eine Gruppe von Informationselementen, die Informationen über Nachlässe liefern, die für die Rechnung als Ganzes gelten. Anmerkung: Abzüge, wie z. B. einbehaltene Steuern, können auch in dieser Gruppe ausgewiesen werden.',
            ],
            'DOCUMENT_LEVEL_CHARGES' => [
                'id' => 'BG-21',
                'type' => 'DOCUMENT_LEVEL_CHARGESType',
                'min' => 1,
                'multiple' => true,
                'description' => 'Eine Gruppe von Informationselementen, die Informationen über Kosten, Zuschläge, und Steuern ndash; ausgenommen die Umsatzsteuer ndash; enthalten, die für die Rechnung als Ganzes gelten.',
            ],
            'DOCUMENT_TOTALS' => [
                'id' => 'BG-22',
                'type' => 'DOCUMENT_TOTALSType',
                'min' => 1,
                'multiple' => false,
                'description' => 'Eine Gruppe von Informationselementen, die die monetären Gesamtbeträge der Rechnung liefern.',
            ],
            'VAT_BREAKDOWN' => [
                'id' => 'BG-23',
                'type' => 'VAT_BREAKDOWNType',
                'min' => 1,
                'multiple' => true,
                'description' => 'Eine Gruppe von Informationselementen, die Informationen über die Umsatzsteueraufschlüsselung in verschiedene Kategorien liefern.',
            ],
            'ADDITIONAL_SUPPORTING_DOCUMENTS' => [
                'id' => 'BG-24',
                'type' => 'ADDITIONAL_SUPPORTING_DOCUMENTSType',
                'min' => 1,
                'multiple' => true,
                'description' => 'Eine Gruppe von Informationselementen mit Informationen über rechnungsbegründende Unterlagen, die Belege für die in der Rechnung gestellten Ansprüche enthalten. Dateinamen rechnungsbegründender Unterlagen müssen innerhalb einer Rechnung eindeutig sein (nicht case-sensitiv). Die Dateinamenserweiterung (extension), in der meist der Typ der Datei angegeben wird, ist dabei Teil des Dateinamens und wird bei der Bestimmung der Eindeutigkeit einbezogen. Anmerkung: Die Gruppe kann verwendet werden, um auf eine dem Erwerber bekannte Dokumentennummer oder ein externes Dokument (referenziert über eine URL als separat herunterladbare Ressource) oder ein eingebettetes Dokument (wie z. B. ein Leistungsnachweis als pdf) zu referenzieren. Von der Möglichkeit der Trennung von Rechnung und rechnungsbegründenden Unterlagen kann insbesondere im Fall großer Anlagen oder sensibler Daten Gebrauch gemacht werden.',
            ],
            'INVOICE_LINE' => [
                'id' => 'BG-25',
                'type' => 'INVOICE_LINEType',
                'min' => 1,
                'multiple' => true,
                'description' => 'Eine Gruppe von Informationselementen, die Informationen über einzelne Rechnungspositionen liefern.',
            ],
            'THIRD_PARTY_PAYMENT' => [
                'id' => 'BG-DEX-09',
                'type' => 'THIRD_PARTY_PAYMENTType',
                'min' => 1,
                'multiple' => true,
                'description' => 'Eine Gruppe von Informationselementen, die Informationen über Fremdforderungen enthalten.',
            ],
        ],
    ],
];
